version: '3.9'
  services:
    web:
      image: 'gitlab/gitlab-ce:13.8.0-ce.0'
      restart: always
      hostname: 'gitlab.tsoutello.com'
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'https://gitlab.tsoutello.com'
      ports:
        - '9797:80'
        - '443:443'
        - '22:22'
      volumes:
        - '/srv/gitlab/config:/etc/gitlab'
        - '/srv/gitlab/logs:/var/log/gitlab'
        - '/srv/gitlab/data:/var/opt/gitlab'